In [1]:
import numpy as np

In [2]:
# Question 1

arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [3]:
# Question 2

arr1,arr2 = (list(map(int,input().split())) for i in range(2))

arr1 = np.array(arr1)
arr2 = np.array(arr2)

print(np.concatenate((arr1,arr2)))

print(np.sort(np.concatenate((arr1,arr2))))

1 3 2
6 4 5
[1 3 2 6 4 5]
[1 2 3 4 5 6]


In [4]:
# Question 3

arr = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])

print(arr.shape,arr.size)

(3, 3) 9


In [5]:
# Question 4

'''
    To convert a 1D array into a 2D array, we can use reshape(a, newshape, order='C').
    
    e.g arr = np.array([ [1,2,3,4,5,6,7,8,9] ]) 
        
        arr.shape O/P: (1, 9)
        
        arr.reshape(3,3)
        
        O/P: array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
    
'''

arr = np.array([ [1,2,3,4,5,6,7,8,9] ])

print(arr,arr.shape) 

print()

arr = arr.reshape(3,3) 

print(arr,arr.shape) 

[[1 2 3 4 5 6 7 8 9]] (1, 9)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [6]:
# Question 5

arr1 = np.array([ [1,1,1] , [2,2,2] , [3,3,3] ])
arr2 = np.array([ [4,4,4] , [5,5,5] , [6,6,6] ])

print(np.vstack((arr1,arr2))) # Stack the arrays in a row-wise sequence
print() 
print(np.hstack((arr1,arr2))) # Stack the arrays in a column-wise sequence

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]

[[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]


In [7]:
# Question 6

arr = np.array([ [1,2,2] , [3,4,5] , [5,6,6] ])

print(np.unique(arr)) 

[1 2 3 4 5 6]


In [9]:
arr = np.array([ [1,2,2] , [1,2,2] , [5,6,6] ])

print(np.unique(arr,return_counts=True)) 

(array([1, 2, 5, 6]), array([2, 4, 1, 2], dtype=int64))
